### ISSUE TITLE
Glitch with drag and drop

### ISSUE THREAD

**Issue by lewweiming** [gilnd/vue3-smooth-dnd#1]
Hi Gilnd, I'd love to use this package as part of my project but could not get it to work as expected.

I've also included a demo to illustrate the issue. What could be wrong?

See https://codesandbox.io/s/optimistic-murdock-jx8wi

**Comment by gilnd** [comment]
Hi @lewweiming , thanks for the feedback.
From a fast analysis turned out this is caused by upgrading vue to the latest version, with version **3.0.11** of vue worked fine!

Will look into this as soon as i can!

Thanks! :)
