### ISSUE TITLE
Screen scroll does not work on mobile 

### ISSUE THREAD

**Issue by lucapu88** [gilnd/vue3-smooth-dnd#19]
When I am using drag n drop on mobile I am prevented from touchmoving the list...I attach video

https://github.com/gilnd/vue3-smooth-dnd/assets/56302007/f4782f4c-d9a5-4909-94b8-95a76803ebaf

Could it be for this css class of yours?

````
.smooth-dnd-disable-touch-action * {
  touch-action: hidden;
  display: block;
}
````

**Comment by lucapu88** [comment]
I have solved it with this, it works smoothly without impacting other things and I would say that this is fine with me.
There is no point in disabling touch events, otherwise there would be no point in using this library. 

````
.smooth-dnd-disable-touch-action * {
  touch-action: auto;
}
````

**Comment by g1lg1l** [comment]
Hey @lucapu88 ty for the feedback!

> .smooth-dnd-disable-touch-action * {
  touch-action: auto;
}

this is probably a dependency injected class, can't do much about it, ty for your solution anyway im sure it will come usefull to others as well!
