### ISSUE TITLE
Plugin does not work with Iframes

### ISSUE THREAD

**Issue by paleacci** [gilnd/vue3-smooth-dnd#2]
Hello,

the plugin does not harmonize with iframes. When you move an item over an iframe, it starts to hang. It should be better that items are also dragged into the iframe and can be edited in it.

If I display the items in the iframe itself, it is somehow as if the items no longer have events.

```html
<Container :key="size" 
  orientation="vertical" 
  group-name="col-items"  
  :drop-placeholder="{ className: 'holder', animationDuration: '200', showOnTop: true }"
  drag-class="test"
  drop-class="drop">
  <template v-for="item in 8" :key="item">
    <Draggable v-if="item">
      <div class="pa-0">
        <div class="pa-2 bg-white tc-dark">
          {{ item }}
        </div>
      </div>
    </Draggable>
  </template>
</Container>
```

**Comment by gilnd** [comment]
Hey @paleacci 
Thanks for the feedback.

This is a known [issue](https://github.com/kutlugsahin/smooth-dnd/issues/11) in [smooth-dnd](https://github.com/kutlugsahin/smooth-dnd), wich is the core dependency of this library.
