### ISSUE TITLE
data from props and it don't work

### ISSUE THREAD

**Issue by Minori-ty** [gilnd/vue3-smooth-dnd#4]
Hi, counld you help me?
when I use the data from props, and it don't work, here it's the mini demo:

https://github.com/Minori-ty/vue3-dnd

Thanks

**Comment by gilnd** [comment]
Hi @Minori-ty 
You can't update props directly in the child component in vue, look at the [vue documentation](https://vuejs.org/guide/components/props.html#one-way-data-flow).

Closing since not related to this package

**Comment by Minori-ty** [comment]
> Hi @Minori-ty You can't update props directly in the child component in vue, look at the [vue documentation](https://vuejs.org/guide/components/props.html#one-way-data-flow).
> 
> Closing since not related to this package

Thank you for answer, I have resolved the problem by watching the props and reassign to an variable
