### ISSUE TITLE
I use the version of vue2. I don't know why an error is reported after importing

### ISSUE THREAD

**Issue by HuangHua1** [gilnd/vue3-smooth-dnd#5]
![1668674768098](https://user-images.githubusercontent.com/6121553/202399914-7ec24d1f-671b-4c33-81d2-8c3f954077f4.jpg)
![1668674812193](https://user-images.githubusercontent.com/6121553/202399933-c81e2d2b-7bd3-46ac-9bde-d6f52f42189b.jpg)
![1668674838599](https://user-images.githubusercontent.com/6121553/202399943-ad8c6bd9-c14b-41cc-b2b9-89b4316afaee.jpg)

**Comment by gilnd** [comment]
Hey @HuangHua1 
If you are using **vue2** you should use [vue-smooth-dnd](https://github.com/kutlugsahin/vue-smooth-dnd), this package is not compatible with vue 2 only vue 3.

Cheers.
